Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "master" do |master|
	  master.vm.network "private_network", ip: "10.10.10.10"
	  master.vm.network "forwarded_port", host: 8886, guest: 80
	  master.vm.network "forwarded_port", host: 8887, guest: 8080
	  master.vm.provision "ansible_local" do |ansible|
	    ansible.provisioning_path = "/vagrant/ansible"
	    ansible.inventory_path = "hosts"
	    ansible.playbook = "playbook.yml"
	    ansible.limit = "all"
	    ansible.verbose = true
	  end
  end
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "10.10.10.11"
    node1.vm.network "forwarded_port", host: 9000, guest: 80
    node1.vm.network "forwarded_port", host: 9001, guest: 8080
    node1.vm.provision "ansible_local" do |ansible|
	    ansible.provisioning_path = "/vagrant/ansible"
	    ansible.inventory_path = "hosts"
	    ansible.playbook = "playbook.yml"
	    ansible.limit = "all"
	    ansible.verbose = true
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "10.10.10.12"
    node2.vm.network "forwarded_port", host: 9002, guest: 80
    node2.vm.network "forwarded_port", host: 9003, guest: 8080
    node2.vm.provision "ansible_local" do |ansible|
	    ansible.provisioning_path = "/vagrant/ansible"
	    ansible.inventory_path = "hosts"
	    ansible.playbook = "playbook.yml"
	    ansible.limit = "all"
	    ansible.verbose = true
    end
  end
end
